---
title: "LDviz d3 Part"
author: "Hugo Carton"
date: today
title-block-banner: true
format:
  html:
    embed-resources: true
    number-sections: true
    toc: true
    df-print: paged
execute: 
  warning: false
  message: false
  include: true
knitr:
  opts_chunk:
    tidy: true
    out.width: 100%
    fig-width: 6
    fig.asp: 0.618
    fig.align: center
    R.options:
      width: 80
editor: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Website presentation

The website is a simple html page containing for the moment 3 major differents parts.
I will go in detail to review each of them.

## Part 1 : Text Area

The Text Area is the part where the user can enter the SparQL request which he wants to see the graph of. Once the request is written, the user just have to use the "send" button under the Text Area.

During the test phase, the request used was this one :

```{SparQL request}

CONSTRUCT{ ?endpoint rdf:value ?sparqlNorm } {
    GRAPH ?g {
    { ?curated <http://www.w3.org/ns/sparql-service-description#endpoint> ?endpoint . }
    UNION { ?curated <http://rdfs.org/ns/void#sparqlEndpoint> ?endpoint . }
    UNION { ?curated <http://www.w3.org/ns/dcat#endpointURL> ?endpoint . }
    ?metadata <http://ns.inria.fr/kg/index#curated> ?curated, ?dataset .
        { ?dataset <http://www.w3.org/ns/prov#wasGeneratedBy> ?activity . }
        UNION { ?metadata <http://www.w3.org/ns/prov#wasGeneratedBy> ?activity .}
        FILTER(CONTAINS(str(?activity), ?sparqlNorm))
        VALUES ?sparqlNorm { "SPARQL10" "SPARQL11" }
    }
    }
    GROUP BY ?endpoint ?sparqlNorm
    ORDER BY ?endpoint ?sparqlNorm
            
```


## Part 2 : Table

The table contains all the different values of all the triplets of each patterns. Those values are spread into 3 columns : source, label, and target. Those columns are the nodes and the links of the graph, and of the obtained dataset.

The table print by default 10 lines of data at a time, but the user can explore them and change the lines.


## Part 3 : Graph Values

The graph values is the graph containing all the different values. It takes all the pattern and all the values, then create the different nodes and links between those nodes.

For the color choices, they can be changed in the parameters of the function. By default, the source nodes are red, and the target nodes are blue. If a node is both source and target (being called by different patterns), then the colors are mixed.





# Things I can maybe add?

Put buttons with the different possible colors for the legend.

Allow to change the number of lines in the dataset.


















